networks:
  shortener:
    name: shortener

services:
  back-end:
    container_name: back-end
    restart: always
    build: back-end
    ports:
      - 3000:3000
    networks:
      - shortener

  front-end:
    container_name: front-end
    depends_on: [ "back-end" ]
    restart: always
    build: front-end
    ports:
      - 80:80
    networks:
      - shortener
